Add Snyk to onboarding
GSA/datagov-deploy pull request #1143
Opened 2019-11-21 22:40 UTC by adborden

2019-11-21 22:52 UTC, mogul approved these changes

2019-11-21 22:53 UTC, mogul requested changes
Please also pair with an offboarding checklist addition

2019-11-22 00:56 UTC, adborden commented
Thanks, fixed!

2019-11-25 17:20 UTC, mogul approved these changes

2019-11-25 17:20 UTC, merged