Replace harvest with datagov_harvest as catalog classic
GSA/datagov-deploy pull request #1792
Opened 2020-06-23 15:03 UTC by avdata99

Start using the `datagov_harvest` to override harvest source form creation
Now we are not able to create `waf-collection` harvester sources.
This is the actual behaviour of catalog classic.
The form add this new fields:
![image](https://user-images.githubusercontent.com/3237309/85419682-c5dba380-b548-11ea-9828-44583c25251b.png)

2020-06-24 01:58 UTC, adborden commented
Thanks @avdata99 can you link to where this extension is implemented? I want to pull in functionality from our custom extensions very deliberately. I think at some point after MVP, we'll want to circle back on all these various extensions for addressing tech debt. Therefore, I want to leave a trail of breadcrumbs so that we know where we want to look back to.... if that makes any sense.

2020-06-24 02:00 UTC, adborden commented
... or datagov_harvest is the new extension? :sweat_smile:

2020-06-24 02:00 UTC, adborden approved these changes

2020-06-24 03:02 UTC, avdata99 commented
> Thanks @avdata99 can you link to where this extension is implemented? I want to pull in functionality from our custom extensions very deliberately. I think at some point after MVP, we'll want to circle back on all these various extensions for addressing tech debt. Therefore, I want to leave a trail of breadcrumbs so that we know where we want to look back to.... if that makes any sense.

Is defined at [geodatagov extension](https://github.com/GSA/ckanext-geodatagov/blob/master/setup.py#L30).


[This class](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/plugins.py#L307) inherit and change behaviour of base harvesters.

We can't add waf-collection sources whitout the form defined in the form defined at `package_form`.

Maybe we can define some issues to move this features in a better way at our new extension. We can then prioritize them and see want we need now and what could be posposed.
Is this a good idea?

2020-06-24 14:30 UTC, avdata99 commented
> ... or datagov_harvest is the new extension?

I created a new issue to cover this: https://github.com/GSA/catalog.data.gov/issues/75

2020-06-24 19:33 UTC, adborden commented
This change was already made in development https://github.com/GSA/catalog.data.gov/pull/74

2020-06-25 13:57 UTC, thejuliekramer commented
@adborden @avdata99 This change does add the collection metadata url which we need for the waf collection harvester but this also causes the same error when trying to harvest a datajson source which worked previously, it changes other fields we need on the form like organization - we need to look into this more

2020-06-25 13:58 UTC, thejuliekramer requested changes
We need to look into this more - it is breaking the datajson harvest flow

2020-06-25 14:23 UTC, avdata99 commented
I try to add other types of sources and I get the same error defined at [Catalog#75](https://github.com/GSA/catalog.data.gov/issues/75).
We will need to fix 75 before merging this PR . I will close and add some reference to reopen after finish 75.

2020-07-20 20:13 UTC, thejuliekramer approved these changes

2020-07-20 20:13 UTC, merged